//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borc
    {
        public int Id { get; set; }
        public int BorcMiktari { get; set; }
        public string Borcadi { get; set; }
        public string Borcaciklama { get; set; }
        public int Odenen { get; set; }
        public Nullable<System.DateTime> OdenenT { get; set; }
    }
}
