//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiBildirim
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Eposta { get; set; }
        public int SiteId { get; set; }
        public int KisiId { get; set; }
        public string Adres { get; set; }
        public bool Onay { get; set; }
    }
}
