//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AptManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AptYonetimEntities : DbContext
    {
        public AptYonetimEntities()
            : base("name=AptYonetimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Bildirim> Bildirim { get; set; }
        public DbSet<Blok> Blok { get; set; }
        public DbSet<Borc> Borc { get; set; }
        public DbSet<KisiBildirim> KisiBildirim { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Site> Site { get; set; }
        public DbSet<Tur> Tur { get; set; }
    }
}
